import "../globals.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Navbar from "../../components/Navbar";
import { Footer } from "@/components";

const lato = Lato({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-cd-bck2">
        <main className={lato.className}>
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
